### ISSUE TITLE
Goal word not accepted

### ISSUE THREAD

**Issue by JFed-9** [c-de-f/tictactordle#1]
I was given the target word of "email", and I knew "_mail". I tried typing email in the end screen twice, but it said it wasn't a word. Then I typed a random word, and it said the word was indeed "email".

**Comment by c-de-f** [comment]
Fixed. Must've gotten botched when cleaning up the vocabulary.

**Comment by JFed-9** [comment]
Awesome! That was fast. No issues so far, closing issue
