### ISSUE TITLE
I'm able to overwrite computer actions

### ISSUE THREAD

**Issue by JFed-9** [c-de-f/tictactordle#4]
If at the beginning of the game (or at any time when there are blank cells), you decide to click every square without typing a letter, then when the computer goes in a square, you may overwrite their guess. The letter and color remain the same as the computer's guess, but it is now an "X" as considered by the game engine, and you may win with an apparent "O" in your line.
![image](https://user-images.githubusercontent.com/19255031/168654445-39154f6d-574d-4374-afbf-3efb394cefc0.png)

**Comment by c-de-f** [comment]
Fixed.

**Comment by JFed-9** [comment]
Looks great. Closing issue
